name: "Go coverage report"
on:
  pull_request:
  push:
    branches:
      # Must run for the default branch!
      - main

jobs:
  coverage:
    uses: giantswarm/github-workflows/.github/workflows/go-coverage.yaml@70d7ae63de12e093aea62012fd952051cc3b2460
    secrets:
      token: "${{ secrets.TAYLORBOT_GITHUB_ACTION }}"
