name: "Go coverage report"
on:
  pull_request:
  push:
    branches:
      - reuse-workflow # TODO: remove before merging
      # It's important that the action also runs on merge to main
      - main

jobs:
  coverage:
    uses: giantswarm/github-workflows/.github/workflows/go-coverage.yaml@d49ddde7f3b5121940496dfd066f507a29deb1e5 # TODO: update to final commit before merging
    secrets:
      token: "${{ secrets.TAYLORBOT_GITHUB_ACTION }}"
