name: "Go coverage report"
on:
  pull_request:
  push:
    branches:
      # Must run for the default branch!
      - main

jobs:
  coverage:
    uses: giantswarm/github-workflows/.github/workflows/go-coverage.yaml@b8331e5e6f42a3f65156a248f01c0980c16c97b6
    secrets:
      token: "${{ secrets.TAYLORBOT_GITHUB_ACTION }}"
