name: "Go coverage report"
on:
  pull_request:
  push:
    branches:
      # Must run for the default branch!
      - main

jobs:
  coverage:
    uses: giantswarm/github-workflows/.github/workflows/go-coverage.yaml@9740d24db0b7baa1b9aff3609f23789e113c6f27
    secrets:
      token: "${{ secrets.TAYLORBOT_GITHUB_ACTION }}"
