name: "Go coverage report"
on:
  pull_request:
  push:
    branches:
      # Must run for the default branch!
      - main

jobs:
  coverage:
    uses: giantswarm/github-workflows/.github/workflows/go-coverage.yaml@f521ed67a6d5dc7ef628138d4bac919f1d3d4079
    secrets:
      token: "${{ secrets.TAYLORBOT_GITHUB_ACTION }}"
